### ISSUE TITLE
cannot run example according to Getting_started in wiki 

### ISSUE THREAD

**Issue by healthyjk** [sensorstorm/StormCV#2]
When I run  E1_GrayScaledTopology.java in eclipse as you mentioned in Getting_started ,I get errors as below. It shows some errors caused by xuggle. But I dont know why. Could you help me?
_______________________________________________________________________________
![20150309233328](https://cloud.githubusercontent.com/assets/7419446/6558082/b938a5d4-c6b4-11e4-8479-1da0d15743e8.png)

**Comment by corneversloot** [comment]
Hi Healtyjk,

Looks like Xuggler (the library used to read video) cannot load the binaries it needs. Looking at the 7th line of your log it looks like it fails to load the library form your /tmp location which i find strange... What OS and IDE are you using?

- Corné

**Comment by healthyjk** [comment]
Hi corneversloot, 
  I use Redhat 5.1 server and Eclipse. When I imported stormCV on my Ubuntu 14.04, it works. 
  Thank you!

**Comment by corneversloot** [comment]
I am afraid Xuggle does not support Redhat; i.e. the jar file does not contain the RHEL binaries which in turn causes the UnsatisfiedLinkError you report. Unfortunatly the OpenCV build we created does not support RHEL either which means you would have to build both on your OS to get it working...

In case you want to do to that:
* see http://www.xuggle.com/xuggler/build for pointers how to build Xuggle
* and see http://docs.opencv.org/2.4.4-beta/doc/tutorials/introduction/desktop_java/java_dev_intro.html for build instructions for OpenCV.

You can also run it within a VM but i do not know if that actually works for you.

I hope this helps!

**Comment by healthyjk** [comment]
Hi corneversloot,
Thank you very much ! I may build the stormCV project on ubuntu. Thank you for your help!
