### ISSUE TITLE
When I Run DeploymentTopology.jar i am getting lasterror meg in Bolts please help me

### ISSUE THREAD

**Issue by sureshk543** [sensorstorm/StormCV#5]
java.lang.UnsatisfiedLinkError: /tmp/linux64_opencv_java248.so: /tmp/linux64_opencv_java248.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch) at java.lang.ClassLoader

**Comment by corneversloot** [comment]
Something goes wrong when loading the OpenCV library packed with StormCV. The library to use depends on the operating system executing the topology and it looks like the system tries to load the wrong library. What operating system are you deploying to?

**Comment by sureshk543** [comment]
i am using ubantu VM 14.04
opencv is a additional installation

**Comment by sureshk543** [comment]
give me a clear description to execute this topaligy

**Comment by sureshk543** [comment]
i am using ubantu OS
i tried so many times getting same error i am new to storm
please solve my issue
opencv is freeware oew to install tell me please solve

On Sat, Oct 10, 2015 at 11:01 PM, Corne Versloot <notifications@github.com>
wrote:

> Something goes wrong when loading the OpenCV library packed with StormCV.
> The library to use depends on the operating system executing the topology
> and it looks like the system tries to load the wrong library. What
> operating system are you deploying to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensorstorm/StormCV/issues/5#issuecomment-147111570>.
>



-- 
Suresh.Kotha

**Comment by corneversloot** [comment]
It should work on Ubuntu 14.04 (although I have never executed StormCV on 14.04). Given the error it seems you try to use the 64 bit library on a 32 bit system. Unfortunately there is no pre-build 32 bit OpenCV library within the StormCV distribution. There are two solutions I can think of:
 - use a 64 bit machine / VM.
 - build the OpenCV library for 32 bit Ubuntu 14.04. See [this tutorial](http://docs.opencv.org/doc/tutorials/introduction/desktop_java/java_dev_intro.html) on the OpenCV website.

As a side note, I would recommend going through the examples before building and deploying a topology on a cluster.
